server:
  port: 8082

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.plasticlove.entity   # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://101.132.64.189:3306/springcloud02             # 数据库名称
    username: root
    password: '0515'
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://plasticlove.cloud1.com:7001/eureka,http://plasticlove.cloud2.com:7002/eureka,http://plasticlove.cloud3.com:7003/eureka
  instance:
    instance-id: cloud-dept02   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址


info:
  app.name: plasticlove-cloud
  company.name: www.plasticlove.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$




