server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://plasticlove.cloud1.com:7001/eureka,http://plasticlove.cloud2.com:7002/eureka,http://plasticlove.cloud3.com:7003/eureka