server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
##  instance:
##    hostname: eureka-server.com
#spring:
#  application:
#    name: eureka-server
